//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoOffVocabulary.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoOffVocabulary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Card 的當地語系化字串。
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Again 的當地語系化字串。
        /// </summary>
        internal static string Again {
            get {
                return ResourceManager.GetString("Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Again (Minutes): 的當地語系化字串。
        /// </summary>
        internal static string AgainMinutes {
            get {
                return ResourceManager.GetString("AgainMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete these cards? 的當地語系化字串。
        /// </summary>
        internal static string AreYouSureYouWantToDeleteTheseCards {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheseCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete these decks? 的當地語系化字串。
        /// </summary>
        internal static string AreYouSureYouWantToDeleteTheseDecks {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheseDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Study (sec): 的當地語系化字串。
        /// </summary>
        internal static string AutoStudysec {
            get {
                return ResourceManager.GetString("AutoStudysec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create 的當地語系化字串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Deck 的當地語系化字串。
        /// </summary>
        internal static string CreateDeck {
            get {
                return ResourceManager.GetString("CreateDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy 的當地語系化字串。
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy (Days): 的當地語系化字串。
        /// </summary>
        internal static string EasyDays {
            get {
                return ResourceManager.GetString("EasyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Deck 的當地語系化字串。
        /// </summary>
        internal static string EditDeck {
            get {
                return ResourceManager.GetString("EditDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Google Text-To-Speech 的當地語系化字串。
        /// </summary>
        internal static string EnableGoogleTextToSpeech {
            get {
                return ResourceManager.GetString("EnableGoogleTextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Memo Always On Top 的當地語系化字串。
        /// </summary>
        internal static string EnableMemoAlwaysOnTop {
            get {
                return ResourceManager.GetString("EnableMemoAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English (United Kingdom) 的當地語系化字串。
        /// </summary>
        internal static string EnglishUnitedKingdom {
            get {
                return ResourceManager.GetString("EnglishUnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English (United States) 的當地語系化字串。
        /// </summary>
        internal static string EnglishUnitedStates {
            get {
                return ResourceManager.GetString("EnglishUnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Good 的當地語系化字串。
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Good (Hours): 的當地語系化字串。
        /// </summary>
        internal static string GoodHours {
            get {
                return ResourceManager.GetString("GoodHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japanese 的當地語系化字串。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage Deck 的當地語系化字串。
        /// </summary>
        internal static string ManageDeck {
            get {
                return ResourceManager.GetString("ManageDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 None 的當地語系化字串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Others 的當地語系化字串。
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parameter 的當地語系化字串。
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename 的當地語系化字串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename Card 的當地語系化字串。
        /// </summary>
        internal static string RenameCard {
            get {
                return ResourceManager.GetString("RenameCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename Deck 的當地語系化字串。
        /// </summary>
        internal static string RenameDeck {
            get {
                return ResourceManager.GetString("RenameDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Deck, Source and Input New Card List: 的當地語系化字串。
        /// </summary>
        internal static string SelectDeckSourceAndInputNewCardList {
            get {
                return ResourceManager.GetString("SelectDeckSourceAndInputNewCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting Parameter 的當地語系化字串。
        /// </summary>
        internal static string SettingParameter {
            get {
                return ResourceManager.GetString("SettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop 的當地語系化字串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Study 的當地語系化字串。
        /// </summary>
        internal static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text-To-Speech (TTS) 的當地語系化字串。
        /// </summary>
        internal static string TextToSpeechTTS {
            get {
                return ResourceManager.GetString("TextToSpeechTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Traditional Chinese 的當地語系化字串。
        /// </summary>
        internal static string TraditionalChinese {
            get {
                return ResourceManager.GetString("TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning!! 的當地語系化字串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web Crawler 的當地語系化字串。
        /// </summary>
        internal static string WebCrawler {
            get {
                return ResourceManager.GetString("WebCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yahoo Dict (EN-&gt;CHT) 的當地語系化字串。
        /// </summary>
        internal static string YahooDictEN_CHT {
            get {
                return ResourceManager.GetString("YahooDictEN_CHT", resourceCulture);
            }
        }
    }
}
